### ISSUE TITLE
Fix paragraph spacing

### ISSUE THREAD

**Issue by JMWebDevelopment** [JMWebDevelopment/crosswinds-framework#33]
WordPress 6.3 messed with the paragraph spacing. Need to fix that.

**Comment by MCKH03** [comment]
Need more information
Specify your problem exactly and tell which file needs to be modified

**Comment by JMWebDevelopment** [comment]
Thanks for replying. I left this issue as a reminder for myself. I've fixed it but forgot to push the changes.
